# --- Script: Study 1 - Simulation Visualization (Figure 3) ---
# This script loads the results generated by the simulation study
# and creates a faceted scatterplot showing how the posterior median
# converges towards the true effect size across different sample sizes,
# prior locations, and prior scales.

# Load required libraries
library(ggplot2) # Core plotting engine
library(easystats) # Provides data_read() and theme_modern() functions
library(rstanarm) # Loaded for consistency with the modeling environment

# --- Section: Exploratory / Diagnostic Plots (Legacy Code) ---

# The following block is commented out but left for reference.
# It was likely used during development to quickly inspect the results
# for each prior scale separately before building the final combined figure.
#
# results <- split(result, result$Scale)
#
# lapply(names(results), function(.i) {
#   dat <- results[[.i]]
#   ggplot(dat, aes(x = as.factor(N), y = Median)) +
#     geom_point(alpha = .01, fill = NA, size = .7) +
#     facet_wrap(~Location) +
#     geom_hline(yintercept = .3, color = "darkred") +
#     theme_lucid() +
#     theme(
#       panel.grid.major.x = element_blank(),
#       panel.grid.minor.x = element_blank()
#     ) +
#     ggtitle(paste0(.i, " prior scale")) +
#     ylim(c(-.75, .75)) +
#     scale_x_discrete(breaks = seq(0, 200, 50), labels = seq(0, 200, 50))
# })

# --- Section: Data Preparation ---

# Read the saved simulation results using the easystats data_read() function
result <- data_read("Example1/Study 1 - Simulations.rds")

# Convert the 'Scale' variable into a factor and assign descriptive labels.
# This ensures that the facets in the final plot have clean, readable titles
# and are ordered correctly (from ultranarrow to wide).
result$Scale <- factor(
  result$Scale,
  labels = c(
    "ultranarrow prior scale",
    "narrow prior scale",
    "medium prior scale",
    "wide prior scale"
  )
)

# Explicitly set the factor levels (acts as a safety measure to guarantee order)
levels(result$Scale) <- c(
  "ultranarrow prior scale",
  "narrow prior scale",
  "medium prior scale",
  "wide prior scale"
)


# --- Section: Building the Main Plot ---

# Initialize the ggplot object
# x-axis: Sample Size (treated as categories/factors to create distinct columns)
# y-axis: The estimated Posterior Median from each simulation run
# color: The Prior Location used for that specific simulation
p <- ggplot(
  result,
  aes(x = as.factor(N), y = Median, color = as.factor(Location))
) +

  # Add a solid reference line representing the "True Effect" (0.3)
  geom_hline(yintercept = 0.3, color = "#5a5a5a", linewidth = 0.6) +

  # Plot individual simulation results as points.
  # Alpha (0.04) makes points highly transparent so density can be seen where
  # points overlap.
  # jitterdodge separates the overlapping points horizontally to prevent a
  # massive visual blob.
  geom_point(
    alpha = 0.04,
    fill = NA,
    size = 0.9,
    position = position_jitterdodge(dodge.width = 0.4, jitter.width = 0.2)
  ) +

  # Create a separate sub-plot (facet) for each Prior Scale
  facet_wrap(~Scale) +

  # Apply a clean, publication-ready theme from the easystats package
  theme_modern(show.ticks = TRUE) +
  theme(strip.text = element_text(size = 12, face = "plain")) +

  # Use a colorblind-friendly palette (Okabe-Ito) to distinguish the 5 prior
  # locations
  scale_color_manual(
    values = unname(see::okabeito_colors(c(
      "purple",
      "blue",
      "green",
      "amber",
      "red"
    )))
  ) +

  # Format the x-axis to only show labels at intervals of 50 (to prevent text
  # overlapping)
  scale_x_discrete(breaks = seq(0, 200, 50), labels = seq(0, 200, 50)) +

  # Adjust legend formatting:
  # - reverse = TRUE ensures the legend order matches the visual stacking of the
  #   points
  # - override.aes makes the legend points fully opaque (alpha = 1) instead of
  #   0.04
  guides(
    colour = guide_legend(reverse = TRUE, override.aes = list(alpha = 1))
  ) +

  # Define axis and legend labels
  labs(
    # title = "Posterior Median by Sample Size, Prior Location and Prior Scale",
    # subtitle = "for True Effect of 0.3",
    y = "Posterior Median",
    x = "Sample Size",
    colour = "Prior Location"
  ) +

  # Restrict the y-axis to the relevant range and define tick marks
  scale_y_continuous(limits = c(-0.3, 0.6), breaks = seq(-0.3, 0.6, 0.3))


# --- Section: Export Final Plot ---

# Save the complete figure as a high-resolution TIFF for publication
ggsave(
  "Figure 3.tiff",
  plot = p,
  device = "tiff",
  scale = 1.2,
  compress = "lzw", # Lossless compression standard for print journals
  width = 17,
  height = 14,
  unit = "cm",
  dpi = 600 # 600 dots-per-inch ensures crisp print quality
)
